### ISSUE TITLE
Keybinding for window management are overwritten by the tmux keybindings

### ISSUE THREAD

**Issue by AMulabeg** [omerxx/tmux-floax#12]
This might fully be an issue on my end, because my default prefix is ctrl-a. Is there a way to overwrite the tmux bindings?
<img width="809" alt="image" src="https://github.com/user-attachments/assets/3a7970bb-82df-407b-b023-3af0c0464459">

**Comment by beatzball** [comment]
I also have C-a as my default and assumed the same, but looked into the code and noticed that the the binds actually set as `C-M-*`

So for `C-M-s` it means while in the floating window that you do not need to trigger the initial tmux trigger of `Ctrl+a` and instead go straight to trigger `Ctrl+Alt+s` which will cause the size down event to occur

I think saying `C-a-*` is a bit misleading and could cause further confusion (as both @AMulabeg and I have encountered)

@omerxx - This is purely a thought/suggestion, but could it make more sense to have the window title suggestions be a bit more like:
`FloaX (Ctrl+Alt+): s 󰘕 / b 󰁌 / f 󰊓 / r 󰑓 / e 󱂬 / d `

**Comment by AMulabeg** [comment]
Thank you for clarifying this. I also think making it more clear what the keybinding are would be a great idea. ++

**Comment by omerxx** [comment]
Hey @AMulabeg, the bindings aren't `Ctrl+a` as mentioned but rather `Ctrl+Alt+<key>`
I'm running C-a myself as the default bind for tmux.

**Comment by omerxx** [comment]
> Thank you for clarifying this. I also think making it more clear what the keybinding are would be a great idea. ++

I thought about it, the one issue is that it takes up space and quickly trim the menu. 
If you're able to  come up with something that's more clear I'm happy to accept the contribution / idea!
Maybe even with some nerd-font magic?

**Comment by AMulabeg** [comment]
I can look into making a nerd-font solution. I personally really prefer either clean or clear situation (I removed the menu from my personal setup).
