### ISSUE TITLE
Floatx assumes prefix is C-a

### ISSUE THREAD

**Issue by mok0** [omerxx/tmux-floax#2]
The title bar of the popup shows help to a number of internal commands, this text assumes the prefix is C-a.

**Comment by ProgmRuanSilva** [comment]
@mok0

Don't understand your point, did you mean that the keys are not working, or the prefix shows is not correctly?

**Comment by mok0** [comment]
No, when the floating panel is drawn on the screen, there is a magenta frame drawn around it. Along the top of that frame there is a number of the subcommands printed, and they all begin with C-a (my prefix is set to C-z).

**Comment by ProgmRuanSilva** [comment]
> Here's a picture, I've scaled it down a bit to save space :-) ![screenshot-2](https://private-user-images.githubusercontent.com/878168/334203454-af168ed9-8790-4994-b9d9-d81f58aa0abe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NTQxODIsIm5iZiI6MTcxNjg1Mzg4MiwicGF0aCI6Ii84NzgxNjgvMzM0MjAzNDU0LWFmMTY4ZWQ5LTg3OTAtNDk5NC1iOWQ5LWQ4MWY1OGFhMGFiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QyMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmQ4MWE5MWJjY2VmMTI2OTlmNDgzOTlhNmIyMWU3YjY0ZTc0NDI5MDQ4ZjVmNjA0MGYyNTUxNWEyZGQ3MTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gxLGrm2CyMmU1zDJ8axEny9P4jNqgfuqyHlw4LqVeGc)

Understood, the keymap on the top bar is not showing your keymap. The plugin currently doesn't have support to it right now, sorry :(
