### ISSUE TITLE
Floax popup attaches itself to an existing tmux session after its own one is destroyed

### ISSUE THREAD

**Issue by yellow-quiet** [omerxx/tmux-floax#24]
After all windows and panes inside a floax popup are closed or the scratch session is destroyed, floax attaches itself to the last session on the session list.

**To reproduce:**
1. Open a tmux session
2. (optional) Create a new tmux session and switch back to the previous one
3. Open a floax popup
4. Close all panes and windows in the popup (or kill the floax session)
5. (optional) Repeat 2-4 until no space is left

**Expected behaviour:**
Floax popup closes itself and returns control to the invoker.

**Actual behaviour:**
Floax popup attaches itself to the last session on the session list, creating a tmux-ception. `:detach-client` is required to close the popup and return control to the invoker.

**Comment by omerxx** [comment]
Thank you for opening this, definitely requires a solution. 
To anyone watching this, if you feel you can contribute feel free, i'll take a look as soon as possible

**Comment by omerxx** [comment]
Fixed by #34
