### ISSUE TITLE
opacity and blur 

### ISSUE THREAD

**Issue by Smithx10** [omerxx/tmux-floax#25]
I typically use some opacity and blur in my windows,  would be nice to be able to see panes behind this one if desired.

**Comment by omerxx** [comment]
You mean set an opacity to a tmux pane?
AFAIK this is not an existing style option, what is an option however is setting `set status-bg default` which takes the underlying setting.
Does this help / other request?
I'll go ahead and close this bc I don't think it can be worked out from the plugin's perspective, but if you feel differently feel free to reopen
