### ISSUE TITLE
Separate key binding for showing and hiding the floating window

### ISSUE THREAD

**Issue by lowdewijk** [omerxx/tmux-floax#27]
It would be great if there could be binding to show and hide the floating window. My motivation is mostly that I am very used to getting rid of popups by pressing the escape key. I'd love to reintroduce, perhaps even a double escape press. 

Thanks for a great plugin! :heart:

**Comment by omerxx** [comment]
Hey @lowdewijk and thanks!
You can basically do this:
```
set -g @floax-bind '-n Escape'
```
would this suffice as a solution?

Feel free to reopen if not.

**Comment by sohanemon** [comment]
> ```
> set -g @floax-bind '-n Escape'
> ```

can i make it work in floax only? not everywhere in tmux. Escape is so important in neovim.
