### ISSUE TITLE
Unable to map key to C-/

### ISSUE THREAD

**Issue by multivac61** [omerxx/tmux-floax#30]
`set -g @floax-bind '-n C-n'` and similar work fine but `set -g @floax-bind '-n C-/'` does not. Any ideas why that is?

Excellent plugin and idea!

**Comment by omerxx** [comment]
Hi! not sure why but I don't think this has to do with floax but with tmux not being able to map `ctrl+/` in the root table...
if you think / find anything please feel free to reopen
